### ISSUE TITLE
Error message in step 6

### ISSUE THREAD

**Issue by aurelim** [rhysf/Synima#19]
Hi, 
Thanks for your work.
But I get an error message in step 6:

Can't find the genome sequence (VIBAE_A.3/VIBAE_A.3.genome.fasta) to get full chromosome lengths: No such file or directory
But my genome files are in the same directory than cds, gff3 and pep files :

├── VIBAE_A.3
│   ├── RBH_blast_PEP
│   │   ├── vs_VIBAE_A.3.blast.m8
│   │   └── vs_Vibrio_aestuarianus_01-032.blast.m8
│   ├── VIBAE_A.3_FINAL_CALLGENES_1.annotation.cds
│   ├── VIBAE_A.3_FINAL_CALLGENES_1.annotation.gff3
│   ├── VIBAE_A.3_FINAL_CALLGENES_1.annotation.gff3.synima-parsed.GFF3
│   ├── VIBAE_A.3_FINAL_CALLGENES_1.annotation.pep
│   ├── VIBAE_A.3_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP
│   ├── VIBAE_A.3_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP.phr
│   ├── VIBAE_A.3_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP.pin
│   ├── VIBAE_A.3_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP.psq
│   └── VIBAE_A.3.genome.fasta
└── Vibrio_aestuarianus_01-032
    ├── RBH_blast_PEP
    │   ├── vs_VIBAE_A.3.blast.m8
    │   └── vs_Vibrio_aestuarianus_01-032.blast.m8
    ├── Vibrio_aestuarianus_01-032_FINAL_CALLGENES_1.annotation.cds
    ├── Vibrio_aestuarianus_01-032_FINAL_CALLGENES_1.annotation.gff3
    ├── Vibrio_aestuarianus_01-032_FINAL_CALLGENES_1.annotation.gff3.synima-parsed.GFF3
    ├── Vibrio_aestuarianus_01-032_FINAL_CALLGENES_1.annotation.pep
    ├── Vibrio_aestuarianus_01-032_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP
    ├── Vibrio_aestuarianus_01-032_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP.phr
    ├── Vibrio_aestuarianus_01-032_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP.pin
    ├── Vibrio_aestuarianus_01-032_FINAL_CALLGENES_1.annotation.pep.synima-parsed.PEP.psq
    └── Vibrio_aestuarianus_01-032.genome.fasta

Maybe the SynIma.pl script will not look for the genome files in the right place? Can you help me point out where to look?

Thanks

**Comment by rhysf** [comment]
I'm not sure i understand your directory contents from above. Can you confirm that VIBAE_A.3.genome.fasta and VIBAE_A.3_FINAL_CALLGENES_1.* are all in the directory VIBAE_A.3, and not RBH_blast_PEP?

If you do have VIBAE_A.3/VIBAE_A.3.genome.fasta in that correct location, then can you please send the full command you used, and the entire output it produced.

Best,
Rhys

**Comment by aurelim** [comment]
Yes, I confirm they are in the genome directory VIBAE_A.3, in which i have also RBH_blast PEP directory.

The command I used : 
perl $DATAWORK/Synima/SynIma.pl -a ${DATA}/Repo_spec.txt.dagchainer.aligncoords -b ${DATA}/Repo_spec.txt.dagchainer.aligncoords.spans -e genome.fasta -g g

DATA is defined as the path for the directory containing the 2 genomes directory and Repo_spec.txt

**Comment by rhysf** [comment]
Can you confirm:

1. The entire output (stderr and stdout) of SynIma.pl
2. That your aligncoords and aligncoords.spans are non-empty files

**Comment by aurelim** [comment]
**The stderr :** 
Running Synima...
making output directory /home1/datahome/blabla/SynIma-output...
Saving genome names from /home1/datawork/blabla/Synima/V_aestu/test_synima/Repo_spec.txt.dagchainer.aligncoords.spans...
Can't find the genome sequence (VIBAE_A.3/VIBAE_A.3.genome.fasta) to get full chromosome lengths: No such file or directory

As it said, an output directory is created in another location : /home1/datahome/blabla/SynIma-output
Synima_output contains Config.txt which is empty
I can confirm that aligncoords and aligncoords.spans are non-empty files.

Do you need to see their content ?

aligncoords.spans : 
VIBAE_A.3;VIBAE_A.3	3877-4068	192	Vibrio_aestuarianus_01-032;VAE032.3	23030-23221	192	-	1	1.00
VIBAE_A.3;VIBAE_A.3	3032-3877	846	Vibrio_aestuarianus_01-032;VAE032.3	22185-23030	846	-	1	1.00
VIBAE_A.3;VIBAE_A.3	2253-3035	783	Vibrio_aestuarianus_01-032;VAE032.3	21406-22188	783	-	1	1.00
VIBAE_A.3;VIBAE_A.3	970-2241	1272	Vibrio_aestuarianus_01-032;VAE032.3	20123-21394	1272	-	1	1.00
VIBAE_A.3;VIBAE_A.3	5116-6351	1236	Vibrio_aestuarianus_01-032;VAE032.3	24269-25504	1236	-	1	1.00

**Comment by rhysf** [comment]
The error arises in the function gather_genome_lengths_for_config in Synima.pm, which assumes you are in the directory that you have run all the analysis. 

Could you try:

cd /home1/datawork/blabla/Synima/V_aestu/test_synima

and then:

perl $DATAWORK/Synima/SynIma.pl -a ${DATA}/Repo_spec.txt.dagchainer.aligncoords -b ${DATA}/Repo_spec.txt.dagchainer.aligncoords.spans -e genome.fasta -g g

and if that doesn't work, please add the full output again.

**Comment by aurelim** [comment]
I ran all the workflow from /home1/datawork/blabla/Synima/V_aestu/test_synima   and still have the same error message : 

Running Synima...
making output directory /home1/datahome/blabla/SynIma-output...
Saving genome names from /home1/datawork/blabla/Synima/V_aestu/test_synima/Repo_spec.txt.dagchainer.aligncoords.spans...
Can't find the genome sequence (VIBAE_A.3/VIBAE_A.3.genome.fasta) to get full chromosome lengths: No such file or directory

and I still get an empty Config.txt in /home1/datahome/amesnil/SynIma-output

**Comment by rhysf** [comment]
The command you've used indicates you're using the default location for the output config file which is $cwd/SynIma-output/config.txt

How could you have Config.txt in /home1/datahome/amesnil/ if your $cwd is /home1/datawork/blabla/Synima/V_aestu/test_synima ?

I think that empty Config.txt is from a previous run - please check the timestamp that it was created or modified. Perhaps delete that folder before running it again.



The first thing that Synima is doing, within Synima.pm is 'making output directory /home1/datahome/blabla/SynIma-output'
which is based on 

$cwd = getcwd 
dirname is $cwd/SynIma-output/

Therefore, it makes no sense that it should say its making an output directory here: 

/home1/datahome/blabla/

when you say you are:

/home1/datawork/blabla/Synima/V_aestu/test_synima



I can see you're not keen on writing your directory structure here (hence 'blabla'). But I believe you are still not in the directory that you ran all the rest of the analysis from.

Can you try the following (which will keep your directory names confidential), and copy all the output:

ls -la

(this will say what files are there)

perl $DATAWORK/Synima/SynIma.pl -a Repo_spec.txt.dagchainer.aligncoords -b Repo_spec.txt.dagchainer.aligncoords.spans -e genome.fasta -g g

(you shouldn't need to specify the aligncoords directories - because you should be in that directory!)

ls -la

(please try those 3 commands, and include the full output here.
Thanks,
Rhys

**Comment by aurelim** [comment]
Maybe the problem is linked with the fact I work on a cluster, so I have to put command on a pbs script which is located on a different directory. 
Indeed I used an interactive job, which allowed me to not use this pbs script and it worked!

**Comment by aurelim** [comment]
So I don't really understand where the problem comes from, probably a mistake in my script...
Sorry I took your time, I should have tried the interactive job sooner. Thank you for your help and for Synima
