### ISSUE TITLE
Empty .aligncoords file

### ISSUE THREAD

**Issue by aswathyseb** [rhysf/Synima#35]
Hi,

Thank you for the tool. This is my first ever attempt at synteny and I have a pair of genomes for which I want to create the plot. 

I am following the commands in github based on the alternative approach using OrthoFinder instead of orthoMCL. However, after running `DAGchainer_from_gene_clusters.pl`  the `.aligncoords` and `.aligncoords.span` files that are created are empty. I tried running it changing `-i` to 2, but still the files are empty.

Could you please help me? Let me know if I can provide any log files that can be useful in resolving the issue?

Thanks,

**Comment by rhysf** [comment]
Hi @aswathyseb 

With the information provided, it is unclear which stage likely didn't work, as it could have been any. 

The first stage is often the trickiest, so if you have a record, or just rerun the first stage - you can see what the output is there, and if you have successfully matched your GFF's to your FASTA files.

Otherwise, you will need to look through all the other files and see which point looks suspicious, and do some investigation that way. If you find an error or warning that you are unsure about, then i'm happy to try and assist.

It is possible that you simply have no syntenic regions between your genomes, but i suspect with an -i 2, you should at least find spurious hits, suggesting an earlier stage has not worked. Keep a note of all the warnings by each step, as that should give a good indication of success, as well as the contents of the files that they produce (e.g. are the BLAST files populated with plenty of hits etc.)

Best,
Rhys

**Comment by aswathyseb** [comment]
Thank you very much for the prompt reply.

I do have a record of the commands that I ran and the output (attached here).

Could you please take a look and see if you can spot any problems?

Thank you
[commands.txt](https://github.com/rhysf/Synima/files/8702707/commands.txt)

**Comment by rhysf** [comment]
Hi,

Yes, your IDs in your peptide files did not properly match up to the GFF in the first step:

0 / 11952 found (GFF entries in ./Repo_spec.txt.all.PEP)
0 / 11952 found (./Repo_spec.txt.all.PEP entries in GFF)

Given that your coding sequence (CDS) FASTA files did match up, it should hopefully be straight forward for you to edit the ID's in your PEP files so they do match, and then run the rest of the pipeline from there. You're probably best deleting all the old intermediate files, or starting it from a new folder.

Best,
Rhys

**Comment by aswathyseb** [comment]
That was the problem and editing IDs in the PEP files resolved the issue. Thank you very much! 

When it plots, the chromosome names of the second genome are  getting cut off, Is there a way to display the names exactly as given in the genome file?

**Comment by rhysf** [comment]
So, i'll close this issue but if you have further issues, feel free to open another up. 

As for names that are clipped off, you can either 
1) choose to shorten or remove words from within the config file, 
2) open the pdf in illustrator and remove clipping masks, or 
3) adjust the height parameter of the figure, allowing more room for the names.
