### ISSUE TITLE
error while executing the last step

### ISSUE THREAD

**Issue by bioinfo17** [rhysf/Synima#4]
Hi,
As per the manual, everything went smooth but I get this error while executing the following command:
perl ../SynIma.pl -a Repo_spec.txt.dagchainer.aligncoords -b Repo_spec.txt.dagchainer.aligncoords.spans -r n
error:
 Can't find the genome sequence (vs./vs..genome.fa) to get full chromosome lengths: No such file or directory

The final step works for the example dataset but not with my genomes. A blank config is generated in the SynIma-output directory.

Please advise. Thanks

**Comment by rhysf** [comment]
I'm going to close this issue now, as it was resolved. For unknown reasons, the Repo_spec.txt.dagchainer.aligncoords.spans file had vs. as column 4 instead of genome;contig. The pipeline has been updated to catch this error and provide a more meaningful error if unexpected input is used. This issue also lead to fixing a separate bug parsing contigs with numerical names.
