### ISSUE TITLE
Issue with GFF file format in synima.pl

### ISSUE THREAD

**Issue by Ramzz18** [rhysf/Synima#6]
Dear Dr. Rhys Farrer,

I am trying to generate synteny plots for chromosomal duplication for our new genome (non-model organism). For this I am trying to look for gene duplication of MYB genes in banana genome. So I tried using synima for our analysis. So for genome and set of MYB genes both have same gff file. I am facing some error and couldnt fix this. I was succesful in running example data sets provided in your pipeline. Please help me out in understanding this and fix this issue as following in DAGchainer_from_gene_clusters.pl. Please let me know if needed can share my data with you.

Error
perl ../util/DAGchainer_from_gene_clusters.pl -r ./Repo_spec.txt -c GENE_CLUSTERS_SUMMARIES.RBH/GENE_CLUSTERS_SUMMARIES.clusters
save_genomes_of_interest...
save_genomes_of_interest: found 2 genomes
save_gene_ids_from_ortholog_file: GENE_CLUSTERS_SUMMARIES.RBH/GENE_CLUSTERS_SUMMARIES.clusters...
save_gene_ids_from_ortholog_file: found 2 genomes
process_orthocluster_results_into_hit_pairs: found 2 genomes
save_gene_struct_from_gff: parsing ./Repo_spec.txt.all.GFF3 for all
Error, already stored info for a feature with ID = all:Ma01_t00010.1 - Check GFF and re-run.

**Comment by rhysf** [comment]
Hi @Ramzz18 

That error is occurring because the script has found a gene called Ma01_t00010.1 in organism 'all' twice, when it is expecting each gene to have a unique identifier. 

Did you have any other errors earlier in the pipeline? in particular the first step of the pipeline Create_full_repo_sequence_databases.pl should check if FASTA and GFF's match correctly.

However, from your question, it sounds like you might be using Synima in a slightly unexpected way. What do you have in your Repo_spec.txt? Those should be distinct genomes (or at least have distinct IDs).

Best,
Rhys

**Comment by Ramzz18** [comment]
Hi Dr. Farrer,

Thank you very much for the response. Yes I am using for same genome. Ok I ll try to fix it with different ids.

**Comment by Ramzz18** [comment]
Hi Dr. Farrer,

Thank you very much for the response. Yes I am using for same genome. Ok I ll try to fix it with different ids.

**Comment by Ramzz18** [comment]
Hii Dr. Farrer,

As per your suggestion, I tried changing ids for a set of gene sequences. with new ids and new gff file as in the attachment. I am still getting id mapping issues. I tried checking from all files and ids are same. But still error to check if FASTA and GFF's match correctly. here am sending the attachments. Please help me to sort out this issue.
[Repo_spec.txt](https://github.com/rhysf/Synima/files/2685111/Repo_spec.txt)

[Repo_spec.txt.all.GFF3.txt](https://github.com/rhysf/Synima/files/2685146/Repo_spec.txt.all.GFF3.txt)

**Comment by rhysf** [comment]
Hi @Ramzz18 ,

I'll be happy to try and help. 

The Repo spec and GFF looked fine. However, having changed the IDs, you'll probably need to run the pipeline from the very start - as all the BLAST IDs will also need to be updated (and i suspect that could cause other issues that will be more difficult to identify). If you do that, and for each step, use the verbose setting (where available), and then reply with any errors and informative warnings that come up, I should hopefully be able to advice from there, and more easily know where in the pipeline the problem is.

**Comment by Ramzz18** [comment]
Dear Dr. Farrer,

Thank you so much for your response for helping me in this. Yes I have started running from beginning after changing ids. Can I have your mailid, some files are too big to upload in this forum. (Mine ramzz.1987@gmail.com
[MYB.annotation.pep.txt](https://github.com/rhysf/Synima/files/2688721/MYB.annotation.pep.txt)
)
[MYB.annotation.pep.txt](https://github.com/rhysf/Synima/files/2688718/MYB.annotation.pep.txt)
[Repo_spec.txt.all.PEP.txt](https://github.com/rhysf/Synima/files/2688719/Repo_spec.txt.all.PEP.txt)

 While running step2, I found some parsing error gene_id not identified for Myb set of files. I tried to remove if any space characters interrupting for running script and still facing this error.
 perl ../util/Blast_grid_all_vs_all.pl -r ./Repo_spec.txt 
fasta_id_to_seq_hash: saving sequences from ./Repo_spec.txt.all.PEP...
Splitting seq dictionary for blasting...
Musa_Acuminata = ./Musa_Acuminata/Musa_Acuminata.annotation.pep.synima-parsed.PEP...
Error:Unable to parse line >Ma_Myb3  from proteins file. Gene_id not defined.

Please find the attachments of protein files. Hope this can be helpful to

**Comment by rhysf** [comment]
This particular issue has now been resolved: Unexpected carriage returns were in the FASTA IDs leading to a parsing error. I have now added a line in Create_full_repo_sequence_databases.pl to remove any carriage returns if present.
